-- Create the leads table
create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  rating numeric,
  address text,
  website text,
  phone text,
  city text,
  status text default 'New',
  email_sent boolean default false,
  whatsapp_sent boolean default false,
  note text,
  
  -- Add a unique constraint to prevent duplicates by name
  constraint leads_name_key unique (name)
);

-- Enable Row Level Security (RLS)
alter table leads enable row level security;

-- Create a policy that allows anyone to read/write (since this is an internal tool protected by app password)
-- In a real production app with users, you'd want stricter policies.
create policy "Enable all access for all users" on leads
for all
using (true)
with check (true);
