import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Register a standard font
Font.register({
    family: 'Helvetica',
    fonts: [
        { src: 'https://fonts.gstatic.com/s/helveticaneue/v1/1Ptsg8zYS_SKggPNyCg4TY1n.ttf' }, // Regular
        { src: 'https://fonts.gstatic.com/s/helveticaneue/v1/1Ptsg8zYS_SKggPNyCg4TY1n.ttf', fontWeight: 'bold' } // Bold (using same for simplicity in this env, usually different)
    ]
});

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
        fontFamily: 'Helvetica'
    },
    header: {
        marginBottom: 30,
        borderBottomWidth: 2,
        borderBottomColor: '#2563EB', // Primary Blue
        paddingBottom: 10
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1E293B'
    },
    subtitle: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 5
    },
    section: {
        margin: 10,
        padding: 10,
    },
    urlText: {
        fontSize: 14,
        marginBottom: 20,
        color: '#2563EB'
    },
    scoreGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 30
    },
    scoreCard: {
        width: '45%',
        padding: 15,
        backgroundColor: '#F8FAFC',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        marginBottom: 10
    },
    scoreTitle: {
        fontSize: 12,
        color: '#64748B',
        marginBottom: 5
    },
    scoreValue: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#0F172A'
    },
    findingSection: {
        marginTop: 20,
        padding: 15,
        backgroundColor: '#F0F9FF',
        borderRadius: 8
    },
    findingTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#0F172A'
    },
    findingItem: {
        fontSize: 12,
        marginBottom: 5,
        color: '#334155'
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 10,
        color: '#94A3B8',
        borderTopWidth: 1,
        borderTopColor: '#E2E8F0',
        paddingTop: 10
    }
});

interface AuditResult {
    performance: number;
    seo: number;
    accessibility: number;
    bestPractices: number;
    finalUrl: string;
    h1Status: 'present' | 'missing' | 'unknown';
}

interface SeoReportPdfProps {
    data: AuditResult;
}

export const SeoReportPdf = ({ data }: SeoReportPdfProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>SEO Audit Report</Text>
                <Text style={styles.subtitle}>Generated by DocScale for Medical Practices</Text>
            </View>

            <Text style={styles.urlText}>Audit for: {data.finalUrl}</Text>

            <View style={styles.scoreGrid}>
                <View style={styles.scoreCard}>
                    <Text style={styles.scoreTitle}>Performance</Text>
                    <Text style={{ ...styles.scoreValue, color: data.performance >= 90 ? '#16A34A' : data.performance >= 50 ? '#CA8A04' : '#DC2626' }}>
                        {data.performance}
                    </Text>
                </View>
                <View style={styles.scoreCard}>
                    <Text style={styles.scoreTitle}>SEO</Text>
                    <Text style={{ ...styles.scoreValue, color: data.seo >= 90 ? '#16A34A' : data.seo >= 50 ? '#CA8A04' : '#DC2626' }}>
                        {data.seo}
                    </Text>
                </View>
                <View style={styles.scoreCard}>
                    <Text style={styles.scoreTitle}>Accessibility</Text>
                    <Text style={{ ...styles.scoreValue, color: data.accessibility >= 90 ? '#16A34A' : data.accessibility >= 50 ? '#CA8A04' : '#DC2626' }}>
                        {data.accessibility}
                    </Text>
                </View>
                <View style={styles.scoreCard}>
                    <Text style={styles.scoreTitle}>Best Practices</Text>
                    <Text style={{ ...styles.scoreValue, color: data.bestPractices >= 90 ? '#16A34A' : data.bestPractices >= 50 ? '#CA8A04' : '#DC2626' }}>
                        {data.bestPractices}
                    </Text>
                </View>
            </View>

            <View style={styles.findingSection}>
                <Text style={styles.findingTitle}>Key Findings</Text>

                <Text style={styles.findingItem}>
                    • H1 Tag Status: {data.h1Status === 'present' ? '✅ Present (Good)' : data.h1Status === 'missing' ? '❌ Missing (Critical Issue)' : '⚠️ Unknown'}
                </Text>
                <Text style={styles.findingItem}>
                    • Mobile Optimization: {data.performance >= 80 ? '✅ Good' : '⚠️ Needs Improvement'}
                </Text>
                <Text style={styles.findingItem}>
                    • Core Web Vitals: {data.performance >= 90 ? '✅ Excellent' : data.performance >= 50 ? '⚠️ Average' : '❌ Poor'}
                </Text>
            </View>

            <View style={{ marginTop: 30 }}>
                <Text style={styles.findingTitle}>Recommendations</Text>
                <Text style={styles.findingItem}>1. {data.h1Status === 'missing' ? 'Add a main H1 heading to your homepage immediately.' : 'Ensure your H1 tag contains your main keyword (e.g., "Dentist in [City]").'}</Text>
                <Text style={styles.findingItem}>2. {data.performance < 50 ? 'Optimize images and reduce script execution time to improve speed.' : 'Maintain current performance by optimizing new images.'}</Text>
                <Text style={styles.findingItem}>3. {data.seo < 90 ? 'Review meta titles and descriptions for all pages.' : 'Continue publishing high-quality content.'}</Text>
            </View>

            <View style={styles.footer}>
                <Text>DocScale - Digital Marketing for Doctors | docscale.in</Text>
            </View>
        </Page>
    </Document>
);
