import React from 'react';

interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
  width?: number | string;
  height?: number | string;
  className?: string;
  // When true, image will be treated as high priority (LCP) and not lazy-loaded
  priority?: boolean;
}

// Responsive Image component:
// - prefers generated WebP/AVIF variants under `/images/optimized/`
// - emits `srcset` for multiple widths
// - supports `priority` to avoid lazy loading (useful for LCP images)
export default function Image({ src, alt, width, height, className, priority, ...props }: ImageProps) {
  // Expect images to be served from /images/ and optimized files available at
  // /images/optimized/<name>-<width>.webp (generated by scripts/optimize-images.js)
  const isAbsolute = src.startsWith('http') || src.startsWith('//');
  let optimizedBase = '';
  let basename = '';
  let ext = '';

  try {
    const url = new URL(src, typeof window !== 'undefined' ? window.location.origin : '');
    const parts = url.pathname.split('/');
    const file = parts.pop() || '';
    basename = file.replace(/\.(jpg|jpeg|png|webp|avif)$/i, '');
    ext = file.split('.').pop() || '';
    optimizedBase = `/images/optimized/${basename}`;
  } catch (err) {
    // fallback: treat src as path
    const parts = src.split('/');
    const file = parts.pop() || '';
    basename = file.replace(/\.(jpg|jpeg|png|webp|avif)$/i, '');
    ext = file.split('.').pop() || '';
    optimizedBase = `/images/optimized/${basename}`;
  }

  const widths = [480, 800, 1200, 1600];
  const webpSrcSet = widths.map(w => `${optimizedBase}-${w}.webp ${w}w`).join(', ');
  const avifSrcSet = widths.map(w => `${optimizedBase}-${w}.avif ${w}w`).join(', ');

  const loadingAttr = priority ? undefined : (props.loading ?? 'lazy');
  const fetchPriority = priority ? 'high' : undefined;

  const imgStyle: React.CSSProperties = {};
  if (!width || !height) {
    // provide a heuristic aspect ratio to reduce CLS when dimensions unknown
    imgStyle.aspectRatio = '16/9';
  }

  return (
    <picture>
      <source srcSet={avifSrcSet} type="image/avif" />
      <source srcSet={webpSrcSet} type="image/webp" />
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={loadingAttr}
        decoding={props.decoding ?? 'async'}
        className={className}
        fetchPriority={fetchPriority as any}
        style={{ width: '100%', height: height ? undefined : 'auto', ...imgStyle }}
        {...props}
      />
    </picture>
  );
}
